name: Mount Warning Tours
favicon: null
layout_spectrum: 0.75271
typography_spectrum: 0.8584079490974545
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#16193B'
    - '#35478C'
    - '#4E7AC7'
    - '#7FB2F0'
    - '#ADD5F7'
  brandStrength: 0.0794334018137306
  lightness: 0.2147791802417487
  saturation: 0.2790952534414828
  rhythmicContrast: 0.9301245731767267
purpose: []
